encurta/urls.py
from django.urls import path

from encurta.views import index, link

app_name = 'encurta'

urlpatterns = [
    path('', index, name='index'),
    path('<int:id_link>', link, name='link'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('encurta.urls')),
    path('usuario/', include('usuario.urls')),
]

usuario/urls.py
from django.urls import path

from usuario.views import login, cadastro, usuarios, logout, meus_links

app_name = 'usuario'

urlpatterns = [
    path('cadastro', cadastro, name='cadastro'),
    path('login', login, name='login'),
    path('logout', logout, name='logout'),
    path('usuarios', usuarios, name='usuarios'),
    path('meus-links', meus_links, name='meus-links'),
]

encurta/models.py
from django.contrib.auth.models import User

from django.db import models

class Url(models.Model):
    url = models.CharField(max_length= 100)

    def get_links(self):
        return Link.objects.filter(url= self)
    
    def get_qtd_links(self):
        return Link.objects.filter(url= self).count()

class Link(models.Model):
    usuario = models.ForeignKey(User, on_delete= models.CASCADE, null= True)
    url = models.ForeignKey(Url, on_delete= models.CASCADE)
    qtd_acessos = models.IntegerField(default= 0)

usuario/models.py
# from django.db import models
# from django.contrib.auth.models import User

# # Create your models here.
# class usuario(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
    
#     def __str__(self) -> str:
#         return f'{self.user.fi}'

encurta/views.py
from django.shortcuts import render, redirect, get_object_or_404
from setup.settings import BASE_DIR

from encurta.actions import encurta_link
from encurta.models import Link, Url

# Create your views here.
def index(request):
    # links_gerados = Link.objects.all()
    # qtd_links_gerados = links_gerados.count()

    # urls = Url.objects.all()
    # qtd_urls_geradas = urls.count()
    
    try:
        link = Link.objects.get(id= request.GET.get('id_link'))
    except:
        link = None


    if request.method == 'POST':
        novo_link = encurta_link(request)
        print(novo_link)

        return redirect(f'/?id_link={novo_link.id}')

    return render(request, 'encurta/index.html',{
        # 'links_gerados': links_gerados, 
        # 'qtd_links_gerados': qtd_links_gerados,
        # 'qtd_urls_geradas': qtd_urls_geradas,
        # 'urls': urls  
        'link': link
    })

def link(request, id_link):
    link = get_object_or_404(Link, id= id_link)

    link.qtd_acessos += 1
    link.save()

    return redirect(link.url.url)

usuario/views.py
from django.contrib.auth.models import User 

from django.shortcuts import render, redirect

from encurta.models import Link

from usuario.actions import cadastrar_usuario, entrar, sair

# Create your views here.
def cadastro(request):
    template_name = 'usuario/cadastro.html'

    if request.method == 'POST':
        novo_usuario = cadastrar_usuario(request)

        return redirect('/')

    return render(request, template_name)


def login(request):
    template_name = 'usuario/login.html'

    if request.POST:
        entrar(request)

        return redirect('/')

    return render(request, template_name)

def logout(request):
    sair(request)

    return redirect('/')


def usuarios(request):
    print(request.user)
    template_name = 'usuario/usuarios.html'

    usuarios = User.objects.all().order_by('first_name')

    return render(request, template_name, {
        'usuarios': usuarios
    })


def meus_links(request):
    template_name = 'usuario/meus-links.html'

    links = Link.objects.filter(usuario= request.user)

    return render(request, template_name, {
        'links': links
    })

templates/encurta/index.html
{% extends 'partials/_base.html' %}

{% load static %}

{% block titulo %}Home{% endblock %}

{% block content %}
    <h1 class="main__titulo">Encurta</h1>

    <form action="{% url 'encurta:index' %}" method="POST">
        {% csrf_token %}
        
        <div class="grupo">
            <label for="campo-url">Insira uma URL</label>
            <input type="text" name="url" placeholder="Ex: https://www.google.com" required>
        </div>

        <button class="botao" type="submit">Encurtar</button>
    </form>

    {% if link %}
        {% include 'encurta/partials/_modal-sucesso.html' %}
    {% endif %}
    
    {% comment %}
    

    <!-- <h2>URLs cadastradas ({{ qtd_urls_geradas }})</h2>

    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>URL</th>
                <th>Quantidade de links</th>
            </tr>
        </thead>

        <tbody>
            {% for url in urls %}
                <tr>
                    <td>{{ url.id }}</td>
                    <td>{{ url.url }}</td>
                    <td>{{ url.get_qtd_links }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <h2>Links gerados ({{ qtd_links_gerados }})</h2>

    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>URL</th>
                <th>Quantidade de acessos</th>
            </tr>
        </thead>

        <tbody>
            {% for link in links_gerados %}
                <tr>
                    <td>{{ link.id }}</td>
                    <td>{{ link.url.url }}</td>
                    <td>{{ link.qtd_acessos }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table> -->
    {% endcomment %}
{% endblock %}

templates/encurta/partials/_modal-sucesso.html
<dialog class="modal modal--confirmacao" data-modal="sucesso">
    <b>URL encurtada com sucesso</b>

    <div class="grupo">
        <p class="texto--12">Link gerado</p>

        <a href="{% url 'encurta:link' link.id %}">https://enc.com/{{ link.id }}</a>
    </div>
</dialog>

templates/partials/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>Encurta | {% block titulo %}{% endblock %}</title>

        <link rel="stylesheet" href="{% static 'assets/css/base/reset.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/base/cores.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/base/tipografia.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/base/base.css' %}">

        <link rel="stylesheet" href="{% static 'assets/css/module/botao.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/module/formulario.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/module/menu.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/module/modal.css' %}">
    </head>

    <body>
        <main>
            {% block content %}{% endblock %}
        </main>
        
        {% include 'partials/_menu.html' %}
        
        <script src="{% static 'assets/js/menu.js' %}"></script>
        <script src="{% static 'assets/js/modal.js' %}"></script>
    </body>
</html>

templates/partials/_menu.html
{% load static %}

<div class="menu__container">
    <nav class="menu oculto" data-menu>
        <a href="{% url 'encurta:index' %}">Home</a>

        {% if not request.user.id %}
            <a href="{% url 'usuario:login' %}">Entrar</a>
            <a href="{% url 'usuario:cadastro' %}">Cadastro</a>
        {% endif %}

        <!-- <a href="{% url 'usuario:usuarios' %}">Usuários</a> -->

        {% if request.user.id %}
            <a href="{% url 'usuario:meus-links' %}">Meus links</a>
            <a href="{% url 'usuario:logout' %}">Sair</a>
        {% endif %}
    </nav>

    <button 
        type="button" 
        class="menu__botao"
        data-menu-botao

        {% if request.user.id %}
            style="background-image: url( {% static 'assets/img/joao.jpg' %} );"
        {% else %}
            style="background-image: url( {% static 'assets/img/Account cricle.svg' %} );"
        {% endif %}
    >    
    </button>
</div>

templates/usuario/cadastro.html
<!-- TODO:
-Confirmar senha
-Validar -->


{% extends 'partials/_base.html' %}

{% load static %}

{% block titulo %}Cadastro{% endblock %}

{% block content %}
    <h1 class="main__titulo">Cadastro</h1>

    <form action="{% url 'usuario:cadastro' %}" method="POST">
        {% csrf_token %}
        
        <div class="grupo">
            <label for="campo-nome">Nome</label>
            <input id="campo-nome" type="text" name="nome" required>
        </div>
        
        <div class="grupo">
            <label for="campo-email">E-mail</label>
            <input id="campo-email" type="email" name="email" required>
        </div>
        
        <div class="grupo">
            <label for="campo-nome-usuario">Nome de usuário</label>
            <input id="campo-nome-usuario" type="text" name="nome-usuario" required>
        </div>
        
        <div class="grupo">
            <label for="campo-senha">Senha</label>
            <input id="campo-senha" type="password" name="senha" required>
        </div>

        <button class="botao" type="submit">Salvar</button>
    </form>
{% endblock %}

templates/usuario/login.html
{% extends 'partials/_base.html' %}

{% load static %}

{% block titulo %}Login{% endblock %}

{% block content %}
    <h1 class="main__titulo">Login</h1>

    <form action="{% url 'usuario:login' %}" method="POST" autocomplete="off">
        {% csrf_token %}

        <div class="grupo">
            <label for="campo-nome-usuario">Nome de usuário</label>
            <input id="campo-nome-usuario" type="text" name="nome-usuario" required>
        </div>
        
        <div class="grupo">
            <label for="campo-senha">Senha</label>
            <input id="campo-senha" type="password" name="senha" required>
        </div>

        <button class="botao" type="submit">Entrar</button>
    </form>
{% endblock %}

templates/usuario/meus-links.html
{% extends 'partials/_base.html' %}

{% load static %}

{% block titulo %}Meus links{% endblock %}

{% block content %}
    <h1 class="main__titulo">Meus links</h1>

    {% for link in links %}
        <div class="grupo">
            <h2 class="texto--20"># <a href="{% url 'encurta:link' link.id %}">enc.io/{{ link.id }}</a></h2>

            <p>URL: <a href="{{ link.url.url }}" class="link">{{ link.url.url }}</a></p>

            {% if link.qtd_acessos %}
                <p class="texto--12 texto--cinza">{{ link.qtd_acessos }} acessos</p>
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}

templates/usuario/usuarios.html
{% extends 'partials/_base.html' %}

{% load static %}

{% block titulo %}Usuários{% endblock %}

{% block content %}
    <h1 class="main__titulo">Usuários</h1>

    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Nome de Usuário</th>
            </tr>
        </thead>

        <tbody>
            {% for usuario in usuarios %}
                <tr>
                    <td>{{ usuario.id }}</td>
                    <td>{{ usuario.first_name }}</td>
                    <td>{{ usuario.username }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}